name: lasuie
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - icu=75.1=hfee45f7_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.50.4=h4237e3c_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.5.2=he92f556_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=h6cefb37_0_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.1
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - chex==0.1.90
      - click==8.2.1
      - datasets==4.0.0
      - dgl==1.1.1
      - dill==0.3.8
      - etils==1.13.0
      - filelock==3.13.1
      - flax==0.10.7
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - grpcio==1.74.0
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - humanize==4.13.0
      - idna==3.10
      - importlib-resources==6.5.2
      - jax==0.6.2
      - jaxlib==0.6.2
      - jinja2==3.1.4
      - joblib==1.5.1
      - lightning-utilities==0.15.2
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.4
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nltk==3.9.1
      - numpy==2.1.2
      - opt-einsum==3.4.0
      - optax==0.2.5
      - orbax-checkpoint==0.11.23
      - packaging==25.0
      - pandas==2.3.2
      - pillow==11.0.0
      - propcache==0.3.2
      - protobuf==6.32.0
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.3
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.5
      - rich==14.1.0
      - rouge==1.0.1
      - rouge-score==0.1.2
      - safetensors==0.6.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - simplejson==3.20.1
      - six==1.17.0
      - sympy==1.13.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.76
      - tokenizers==0.21.4
      - toolz==1.0.0
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchmetrics==1.8.1
      - torchsummary==1.5.1
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.55.4
      - treescope==0.1.10
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /Users/mikolajczaplejewicz/miniforge3/envs/lasuie
